Algoritmo "cont"
// 
// Jailson 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/09/2021
Var
// Seção de Declarações das variáveis 
r, x:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para x de 1 ate 5 passo 1 faca
   escreva("Digite o valor de X: ")
   leia(x)
   r<-x*3
   escreval("O valor é: ",r,)
   fimpara
Fimalgoritmo