Algoritmo "idadeemdias"
// 
//                Jailson Costa
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Guilherme Oliveira
// Data atual  : 25/08/2021
Var
// Seção de Declarações das variáveis 
anos,num:inteiro
r1:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite sua idade")
  leia(num)
  r1 <- num*365
  escreval("voce tem", r1, " dias de vida")

Fimalgoritmo