Algoritmo "valormaiorque10"
// 
// Jailson 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/08/2021
Var
// Seção de Declarações das variáveis 
 v:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("digite um valor: ")
 leia(v)
 se v > 10 entao
  escreval("É maior que 10!")
  fimse
 se v < 10 entao
 escreval("Não é maior que 10!")
 fimse

Fimalgoritmo